--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -77,4 +77,4 @@
       - name: Clean docker-compose
         run: |
           docker compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
-          docker compose -f ./tests/docker-compose.yml down
+          docker compose -f ./tests/docker-compose.yml down